<script src="/template/js/vendor/jquery-2.2.4.min.js"></script>
<script src="/template/js/popper.min.js"></script>
<script src="/template/js/vendor/bootstrap.min.js"></script>			
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>		
<script src="/template/js/jquery-ui.js"></script>					
<script src="/template/js/easing.min.js"></script>			
<script src="/template/js/hoverIntent.js"></script>
<script src="/template/js/superfish.min.js"></script>	
<script src="/template/js/jquery.ajaxchimp.min.js"></script>
<script src="/template/js/jquery.magnific-popup.min.js"></script>						
<script src="/template/js/jquery.nice-select.min.js"></script>					
<script src="/template/js/owl.carousel.min.js"></script>							
<script src="/template/js/mail-script.js"></script>	
<script src="/template/js/main.js"></script>	